standard_ban = "Only scrubs play Standard."

modern_ban = "**Modern** includes cards from **Eighth Edition** to today.\n" + "The following cards are banned in Modern:\n" + "Ancestral Vision\n" + "Ancient Den\n" + "Birthing Pod\n" + "Blazing Shoal\n" + "Bloodbraid Elf\n" + "Chrome Mox\n" + "Cloudpost\n" + "Dark Depths\n" + "Deathrite Shaman\n" + "Dig Through Time\n" + "Dread Return\n" + "Glimpse of Nature\n" + "Great Furnace\n" + "Green Sun's Zenith\n" + "Hypergenesis\n" + "Jace, the Mind Sculptor\n" + "Mental Misstep\n" + "Ponder\n" + "Preordain\n" + "Punishing Fire\n" + "Rite of Flame\n" + "Seat of the Synod\n" + "Second Sunrise\n" + "Seething Song\n" + "Sensei's Divining Top\n" + "Stoneforge Mystic\n" + "Skullclamp\n" + "Sword of the Meek\n" + "Treasure Cruise\n" + "Tree of Tales\n" + "Umezawa's Jitte\n" + "Vault of Whispers\n"

legacy_ban = "All **ante**, **dexterity**, and **Conspiracy** cards are banned in Legacy.\n" + "The following cards are banned in Legacy:\n" + "Ancestral Recall\n" + "Balance\n" + "Bazaar of Baghdad\n" + "Black Lotus\n" + "Channel\n" + "Demonic Consultation\n" + "Demonic Tutor\n" + "Dig Through Time\n" + "Earthcraft\n" + "Fastbond\n" + "Flash\n" + "Frantic Search\n" + "Goblin Recruiter\n" + "Gush\n" + "Hermit Druid\n" + "Imperial Seal\n" + "Library of Alexandria\n" + "Mana Crypt\n" + "Mana Drain\n" + "Mana Vault\n" + "Memory Jar\n" + "Mental Misstep\n" + "Mind Twist\n" + "Mind's Desire\n" + "Mishra's Workshop\n" + "Mox Emerald\n" + "Mox Jet\n" + "Mox Pearl\n" + "Mox Ruby\n" + "Mox Sapphire\n" + "Mystical Tutor\n" + "Necropotence\n" + "Oath of Druids\n" + "Shahrazad\n" + "Skullclamp\n" + "Sol Ring\n" + "Strip Mine\n" + "Survival of the Fittest\n" + "Time Vault\n" + "Time Walk\n" + "Timetwister\n" + "Tinker\n" + "Tolarian Academy\n" + "Treasure Cruise\n" + "Vampiric Tutor\n" + "Wheel of Fortune\n" + "Windfall\n" + "Yawgmoth's Bargain\n" + "Yawgmoth's Will\n"

vintage_ban = "All **ante**, **dexterity**, and **Conspiracy** cards are banned in Vintage.\n" + "The following cards are restricted in Vintage:\n" + "Ancestral Recall\n" + "Balance\n" + "Black Lotus\n" + "Brainstorm\n" + "Chalice of the Void\n" + "Channel\n" + "Demonic Consultation\n" + "Demonic Tutor\n" + "Dig Through Time\n" + "Fastbond\n" +  "Flash\n" + "Imperial Seal\n" +  "Library of Alexandria\n" + "Lion's Eye Diamond\n" + "Lotus Petal\n" + "Mana Crypt\n" + "Mana Vault\n" + "Memory Jar\n" + "Merchant Scroll\n" + "Mind's Desire\n" + "Mox Emerald\n" + "Mox Jet\n" + "Mox Pearl\n" + "Mox Ruby\n" + "Mox Sapphire\n" + "Mystical Tutor\n" + "Necropotence\n" + "Ponder\n" + "Sol Ring\n" + "Strip Mine\n" + "Time Vault\n" + "Time Walk\n" + "Timetwister\n" + "Tinker\n" + "Tolarian Academy\n" + "Treasure Cruise\n" + "Trinisphere\n" + "Vampiric Tutor\n" + "Wheel of Fortune\n" + "Windfall\n" + "Yawgmoth's Bargain\n" + "Yawgmoth's Will\n"

edh_ban = "All **ante**, **dexterity**, and **Conspiracy** cards are banned in Commander.\n" + "The following cards are banned in Commander:\n" + "Ancestral Recall\n" + "Balance\n" + "Biorhythm\n" + "Black Lotus\n" + "Braids, Cabal Minion\n" + "Coalition Victory\n" + "Channel\n" + "Emrakul, the Aeons Torn\n" + "Erayo, Soratami Ascendant\n" + "Fastbond\n" + "Gifts Ungiven\n" + "Griselbrand\n" + "Karakas\n" + "Library of Alexandria\n" + "Limited Resources\n" + "Mox Emerald\n" + "Mox Jet\n" + "Mox Pearl\n" + "Mox Ruby\n" + "Mox Sapphire\n" + "Painter's Servant\n" + "Panoptic Mirror\n" + "Primeval Titan\n" + "Protean Hulk\n" + "Recurring Nightmare\n" + "Rofellos, Llanowar Emissary\n" + "Shahrazad\n" + "Sundering Titan\n" + "Sway of the Stars\n" + "Sylvan Primordial\n" + "Time Vault\n" + "Time Walk\n" + "Tinker\n" + "Tolarian Academy\n" + "Trade Secrets\n" + "Upheaval\n" + "Worldfire\n" + "Yawgmoth's Bargain\n"
